services:
  kumulus-agent:
    image: kumulus-agent
    container_name: kumulus-agent
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./mnemonic.txt:/run/secrets/MNEMONIC_SECRET:ro
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "${DOCKER_GID}"